import { addDays, format } from "date-fns";
import type { Booking, Listing, Review, User } from "./types";

export const iso = (d: Date) => format(d, "yyyy-MM-dd");
export const daysFromNow = (n: number) => iso(addDays(new Date(), n));

/* ---------------------------------- images --------------------------------- */
const IMG = {
  aframe: "https://image.qwenlm.ai/generated-images/0d9123ac-4f52-4035-b11e-cce6aabe680b/_result.png",
  loft: "https://image.qwenlm.ai/generated-images/6dc1a153-d6d0-4954-aa5e-1ffd21334140/_result.png",
  beach: "https://image.qwenlm.ai/generated-images/19af859e-08df-48ad-83d7-79f809c92d7c/_result.png",
  treehouse: "https://image.qwenlm.ai/generated-images/7507c55b-1b39-4c49-849b-0b73349a5c01/_result.png",
  villa: "https://image.qwenlm.ai/generated-images/35e769af-6c99-446a-9b21-f7b8d432db85/_result.png",
  chalet: "https://image.qwenlm.ai/generated-images/eb58db7a-655a-4088-bb6c-61a47d6251ca/_result.png",
  casita: "https://image.qwenlm.ai/generated-images/5a092472-92d5-45ec-9f8c-a2089283873b/_result.png",
  houseboat: "https://image.qwenlm.ai/generated-images/2eed9ac6-0733-44c5-97e1-788cb7fd5d93/_result.png",
  farmhouse: "https://image.qwenlm.ai/generated-images/41f2b310-f95e-4f4e-9ba8-5029d3c2296c/_result.png",
  glass: "https://image.qwenlm.ai/generated-images/90a3e478-de91-41e0-849b-1495d32d12c8/_result.png",
};

export const PHOTO_POOL: { src: string; label: string }[] = [
  { src: IMG.aframe, label: "Highland A-frame" },
  { src: IMG.loft, label: "Brewery loft" },
  { src: IMG.beach, label: "Chamo shore house" },
  { src: IMG.treehouse, label: "Juniper treehouse" },
  { src: IMG.villa, label: "Two-lakes villa" },
  { src: IMG.chalet, label: "Timber chalet" },
  { src: IMG.casita, label: "Jugol courtyard house" },
  { src: IMG.houseboat, label: "Lakeboat" },
  { src: IMG.farmhouse, label: "Tis Abay farmhouse" },
  { src: IMG.glass, label: "Entoto glass house" },
];

const gallery = (src: string, noun: string) => [
  { caption: `${noun} — main view`, scale: 1, pos: "50% 50%" },
  { caption: "Living area", scale: 1.9, pos: "18% 62%" },
  { caption: "Morning light", scale: 1.7, pos: "78% 30%" },
  { caption: "The details", scale: 2.3, pos: "55% 78%" },
];

/* ---------------------------------- towns ---------------------------------- */
export const TOWNS = [
  { name: "Bahir Dar", x: 293, y: 214, note: "Lake Tana & the Blue Nile Falls" },
  { name: "Lalibela", x: 405, y: 186, note: "Churches carved from living rock" },
  { name: "Addis Ababa", x: 383, y: 371, note: "The capital at 2,355 m" },
  { name: "Harar", x: 607, y: 354, note: "Walled city, hyena nights" },
  { name: "Arba Minch", x: 303, y: 556, note: "Between two lakes" },
  { name: "Semien Highlands", x: 319, y: 118, note: "Gateway to the roof of Africa" },
];

export const townCoords = (name: string) => {
  const t = TOWNS.find((t) => t.name === name) ?? TOWNS[0];
  return { x: t.x, y: t.y };
};

/* --------------------------------- amenity meta ----------------------------- */
export const AMENITIES = [
  "Wifi",
  "Kitchen",
  "Free parking",
  "Hot tub",
  "Fireplace",
  "AC",
  "Washer",
  "EV charger",
  "Water access",
  "Sauna",
  "Workspace",
  "Pets allowed",
  "Breakfast basket",
  "Stargazing deck",
];

export const CATEGORIES = [
  "All stays",
  "Highlands",
  "Lakeshore",
  "Treehouses",
  "Heritage",
  "Timberline",
  "Countryside",
  "Design",
];

/* ----------------------------------- users ---------------------------------- */
export const hash = (s: string) => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  return `h${h.toString(16)}`;
};

export const SEED_USERS: User[] = [
  {
    id: "u-maya",
    name: "Meron Tadesse",
    email: "host@haven.demo",
    passHash: hash("buna-gebeta-8"),
    provider: "email",
    hue: 152,
    superhost: true,
    joined: "2019-04-12",
  },
  {
    id: "u-jonas",
    name: "Yonas Bekele",
    email: "traveler@haven.demo",
    passHash: hash("teff-injera-4"),
    provider: "email",
    hue: 32,
    joined: "2021-09-03",
  },
  { id: "u-theo", name: "Dawit Alemu", email: "dawit@haven.demo", passHash: hash("x"), provider: "email", hue: 210, superhost: true, joined: "2018-06-21" },
  { id: "u-priya", name: "Selam Girma", email: "selam@haven.demo", passHash: hash("x"), provider: "email", hue: 268, joined: "2020-01-15" },
  { id: "u-elena", name: "Hana Tesfaye", email: "hana@haven.demo", passHash: hash("x"), provider: "email", hue: 355, superhost: true, joined: "2017-11-02" },
];

/* --------------------------------- listings --------------------------------- */
export const SEED_LISTINGS: Listing[] = [
  {
    id: "l-tree",
    hostId: "u-maya",
    title: "Juniper Hollow Treehouse",
    type: "Treehouse",
    town: "Semien Highlands",
    region: "Ethiopia",
    price: 196,
    cleaningFee: 65,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 340,
    description:
      "Twenty-two feet up in an ancient juniper on the Semien escarpment, Juniper Hollow is a one-room hideout reached by rope bridge and lantern light. Mornings arrive with thick-billed ravens and valley fog; evenings end on the wraparound deck while the wood stove ticks. The outdoor rain shower is the whole point.",
    amenities: ["Wifi", "Fireplace", "Breakfast basket", "Stargazing deck", "Workspace"],
    photo: IMG.treehouse,
    gallery: gallery(IMG.treehouse, "Juniper Hollow"),
    mapX: 345,
    mapY: 138,
    rating: 4.99,
    reviewCount: 301,
    tags: ["Treehouses", "Highlands"],
    status: "active",
    views: 4180,
    createdAt: "2021-05-14",
  },
  {
    id: "l-casita",
    hostId: "u-maya",
    title: "Jugol Courtyard House",
    type: "Courtyard house",
    town: "Harar",
    region: "Ethiopia",
    price: 148,
    cleaningFee: 48,
    guests: 3,
    beds: 1,
    baths: 1,
    sqft: 520,
    description:
      "Inside the thousand-year-old Jugol walls, a hand-plastered courtyard house painted the blue of Harar's famous doors. Thick walls keep it cool at noon and warm at midnight; the door opens onto a terrace with a soaking tub pointed at the minarets. At dusk the hyena men call just beyond the gate — the bravest guests go watch.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Hot tub", "Pets allowed", "Stargazing deck"],
    photo: IMG.casita,
    gallery: gallery(IMG.casita, "Jugol House"),
    mapX: 620,
    mapY: 372,
    rating: 4.94,
    reviewCount: 189,
    tags: ["Heritage", "Design"],
    status: "active",
    views: 2644,
    createdAt: "2022-03-02",
  },
  {
    id: "l-glass",
    hostId: "u-maya",
    title: "Entoto Glass House",
    type: "Glass house",
    town: "Addis Ababa",
    region: "Ethiopia",
    price: 252,
    cleaningFee: 72,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 410,
    description:
      "Four glass walls, one wood stove, zero curtains — perched on Mount Entoto's eucalyptus slopes above the glittering grid of Addis. Watch storms cross the valley from the sunken reading pit, then let the underfloor heating and a very good jebena do the rest. Blackout blinds exist; you'll rarely use them.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Workspace", "EV charger", "Washer"],
    photo: IMG.glass,
    gallery: gallery(IMG.glass, "Entoto Glass"),
    mapX: 396,
    mapY: 344,
    rating: 4.97,
    reviewCount: 240,
    tags: ["Highlands", "Design"],
    status: "active",
    views: 5102,
    createdAt: "2023-01-19",
  },
  {
    id: "l-aframe",
    hostId: "u-theo",
    title: "Lasta Highlands A-Frame",
    type: "A-frame",
    town: "Lalibela",
    region: "Ethiopia",
    price: 214,
    cleaningFee: 60,
    guests: 4,
    beds: 2,
    baths: 1,
    sqft: 640,
    description:
      "A timber A-frame on the Lasta ridge, a twenty-minute walk from Lalibela's rock-hewn churches. The triangle window frames the escarpment like a painting that changes every hour; the loft sleeps two under a sky window. Priests' chant drifts up at dawn, and the wood stove keeps its heat until noon.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Free parking", "Sauna", "Pets allowed"],
    photo: IMG.aframe,
    gallery: gallery(IMG.aframe, "Lasta A-Frame"),
    mapX: 392,
    mapY: 162,
    rating: 4.96,
    reviewCount: 212,
    tags: ["Highlands", "Heritage", "Timberline"],
    status: "active",
    views: 3320,
    createdAt: "2020-10-08",
  },
  {
    id: "l-loft",
    hostId: "u-priya",
    title: "Old Brewery Loft, Piassa",
    type: "Loft",
    town: "Addis Ababa",
    region: "Ethiopia",
    price: 178,
    cleaningFee: 55,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 880,
    description:
      "The top floor of an old St. George brewery annex in Piassa — arched brick, oak floors, warm light crossing them all day long. Roastery row and Merkato's Saturday bustle are two blocks away; the record player is stocked with Tilahun Gessesse and the bathtub is deep.",
    amenities: ["Wifi", "Kitchen", "Washer", "Workspace", "AC"],
    photo: IMG.loft,
    gallery: gallery(IMG.loft, "Brewery Loft"),
    mapX: 370,
    mapY: 388,
    rating: 4.85,
    reviewCount: 98,
    tags: ["Design"],
    status: "active",
    views: 1512,
    createdAt: "2022-08-27",
  },
  {
    id: "l-beach",
    hostId: "u-elena",
    title: "Chamo Shore House",
    type: "Shore house",
    town: "Arba Minch",
    region: "Ethiopia",
    price: 342,
    cleaningFee: 110,
    guests: 8,
    beds: 4,
    baths: 3,
    sqft: 2100,
    description:
      "Shore grass, crocodile sunning spots and a veranda that ends at the water. Chamo Shore House sleeps eight across four quiet bedrooms, with a bunk room the kids will claim first and a screened porch built for long dinners. The plains of Nechisar shimmer beyond the lake; hot springs steam a mile away.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Washer", "Water access", "Pets allowed", "Breakfast basket"],
    photo: IMG.beach,
    gallery: gallery(IMG.beach, "Chamo Shore"),
    mapX: 322,
    mapY: 578,
    rating: 4.92,
    reviewCount: 167,
    tags: ["Lakeshore"],
    status: "active",
    views: 2980,
    createdAt: "2019-06-30",
  },
  {
    id: "l-villa",
    hostId: "u-elena",
    title: "Two-Lakes Cliff Villa",
    type: "Villa",
    town: "Arba Minch",
    region: "Ethiopia",
    price: 410,
    cleaningFee: 140,
    guests: 10,
    beds: 5,
    baths: 4,
    sqft: 3200,
    description:
      "White walls, olive trees and an infinity edge suspended between Lake Abaya and Lake Chamo — the view that gave the town its name. The shaded loggia table seats twelve, the pool faces west, and the fruit market's evening bustle is a ten-minute stroll downhill.",
    amenities: ["Wifi", "Kitchen", "Free parking", "AC", "Water access", "Workspace", "EV charger"],
    photo: IMG.villa,
    gallery: gallery(IMG.villa, "Two-Lakes Villa"),
    mapX: 288,
    mapY: 526,
    rating: 4.88,
    reviewCount: 76,
    tags: ["Lakeshore", "Design"],
    status: "active",
    views: 1874,
    createdAt: "2023-05-11",
  },
  {
    id: "l-chalet",
    hostId: "u-theo",
    title: "Walia Timber Chalet",
    type: "Chalet",
    town: "Semien Highlands",
    region: "Ethiopia",
    price: 365,
    cleaningFee: 95,
    guests: 8,
    beds: 4,
    baths: 2,
    sqft: 1900,
    description:
      "Hand-cut juniper timber, a stone hearth you could stand inside, and frost that piles blue against the windows at 3,200 metres. The chalet sits at the last bend before the escarpment trail — gelada troops commute past breakfast and walia ibex graze the rim. The boot room has heated floors; the cocoa tin is never empty.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Free parking", "Hot tub", "Sauna"],
    photo: IMG.chalet,
    gallery: gallery(IMG.chalet, "Walia Chalet"),
    mapX: 332,
    mapY: 98,
    rating: 4.9,
    reviewCount: 143,
    tags: ["Timberline", "Highlands"],
    status: "active",
    views: 2210,
    createdAt: "2018-12-01",
  },
  {
    id: "l-boat",
    hostId: "u-priya",
    title: "The Tana Ark",
    type: "Lakeboat",
    town: "Bahir Dar",
    region: "Ethiopia",
    price: 226,
    cleaningFee: 58,
    guests: 4,
    beds: 2,
    baths: 1,
    sqft: 560,
    description:
      "Moored off the Zeghe Peninsula where the coffee groves meet the water, The Tana Ark rocks you to sleep better than any mattress you own. Cedar interior, a tiny galley that does enormous breakfasts, and a rowboat tied alongside for morning loops of the lake. Hippos surface at dusk, at a respectful distance.",
    amenities: ["Wifi", "Kitchen", "Water access", "Breakfast basket", "Pets allowed"],
    photo: IMG.houseboat,
    gallery: gallery(IMG.houseboat, "The Tana Ark"),
    mapX: 280,
    mapY: 196,
    rating: 4.81,
    reviewCount: 64,
    tags: ["Lakeshore"],
    status: "active",
    views: 1108,
    createdAt: "2024-02-14",
  },
  {
    id: "l-farm",
    hostId: "u-elena",
    title: "Tis Abay Farmhouse",
    type: "Farmhouse",
    town: "Bahir Dar",
    region: "Ethiopia",
    price: 289,
    cleaningFee: 85,
    guests: 9,
    beds: 4,
    baths: 2,
    sqft: 2600,
    description:
      "A stone farmhouse at the end of a juniper drive, with a working teff field on one side and the roar of the Blue Nile Falls on the other. Eggs arrive from the next field; tej is poured in the evenings. The long table in the kitchen has hosted four generations of Sunday lunches.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Fireplace", "Washer", "Pets allowed", "Breakfast basket", "Workspace"],
    photo: IMG.farmhouse,
    gallery: gallery(IMG.farmhouse, "Tis Abay"),
    mapX: 260,
    mapY: 242,
    rating: 4.87,
    reviewCount: 122,
    tags: ["Countryside", "Heritage"],
    status: "active",
    views: 1980,
    createdAt: "2020-04-22",
  },
];

/* --------------------------------- bookings --------------------------------- */
const bk = (
  id: string,
  listingId: string,
  travelerId: string,
  travelerName: string,
  start: number,
  nights: number
): Booking => {
  const listing = SEED_LISTINGS.find((l) => l.id === listingId)!;
  const nightly = nights * listing.price;
  const service = Math.round(nightly * 0.12);
  return {
    id,
    listingId,
    travelerId,
    travelerName,
    checkIn: daysFromNow(start),
    checkOut: daysFromNow(start + nights),
    guests: Math.min(2, listing.guests),
    nights,
    total: nightly + listing.cleaningFee + service,
    breakdown: { nightly, cleaning: listing.cleaningFee, service },
    status: "confirmed",
    createdAt: daysFromNow(start - 12),
  };
};

export const SEED_BOOKINGS: Booking[] = [
  bk("b-1", "l-beach", "u-jonas", "Yonas Bekele", 21, 5),
  bk("b-2", "l-aframe", "u-jonas", "Yonas Bekele", 45, 4),
  bk("b-3", "l-loft", "u-jonas", "Yonas Bekele", -30, 4),
  bk("b-4", "l-tree", "u-theo", "Dawit Alemu", 10, 3),
  bk("b-5", "l-glass", "u-elena", "Hana Tesfaye", 5, 4),
  bk("b-6", "l-casita", "u-priya", "Selam Girma", -12, 3),
  bk("b-7", "l-beach", "u-theo", "Dawit Alemu", 30, 4),
  bk("b-8", "l-chalet", "u-jonas", "Yonas Bekele", -60, 3),
];

/* ---------------------------------- reviews --------------------------------- */
export const SEED_REVIEWS: Review[] = [
  { id: "r1", listingId: "l-tree", author: "Amara", date: daysFromNow(-9), rating: 5, text: "The rope bridge at dusk is genuinely magical. Meron left warm dabo bread and white honey — we almost missed checkout on purpose." },
  { id: "r2", listingId: "l-tree", author: "Bereket", date: daysFromNow(-41), rating: 5, text: "Best sleep of my life, and I mean that clinically. Ravens announced the dawn; the valley fog did the rest." },
  { id: "r3", listingId: "l-tree", author: "Liya", date: daysFromNow(-88), rating: 5, text: "Photos don't do the height justice. Bring a headlamp and zero regrets." },
  { id: "r4", listingId: "l-casita", author: "Mikias", date: daysFromNow(-16), rating: 5, text: "Soaked in the tub as the minarets caught the last light. The hyena men calling at dusk is real — go watch." },
  { id: "r5", listingId: "l-casita", author: "Nardos", date: daysFromNow(-52), rating: 4, text: "Donkeys woke us at 6am. Five stars for them, four for the thin courtyard curtain." },
  { id: "r6", listingId: "l-glass", author: "Tigist", date: daysFromNow(-7), rating: 5, text: "A storm rolled through on night two and we watched all of Addis glitter below from the reading pit. Unreal." },
  { id: "r7", listingId: "l-glass", author: "Abel", date: daysFromNow(-33), rating: 5, text: "The jebena coffee setup alone deserves a review. Worked remotely for a week above the city — zero complaints." },
  { id: "r8", listingId: "l-aframe", author: "Sara", date: daysFromNow(-20), rating: 5, text: "That triangle window is a moving painting. Chant drifted up from the churches at dawn — I've never slept better." },
  { id: "r9", listingId: "l-aframe", author: "Yohannes", date: daysFromNow(-64), rating: 5, text: "Cozy is an overused word; this earns it. Firewood stacked, loft warm, Lasta quiet." },
  { id: "r10", listingId: "l-loft", author: "Rahel", date: daysFromNow(-11), rating: 5, text: "Light moves through those brick arches all day. The Tilahun Gessesse records got heavy rotation." },
  { id: "r11", listingId: "l-loft", author: "Samuel", date: daysFromNow(-47), rating: 4, text: "Gorgeous space, Merkato noise on market mornings — bring earplugs or join the crowd." },
  { id: "r12", listingId: "l-beach", author: "Bete", date: daysFromNow(-5), rating: 5, text: "Eight of us, zero collisions. Screened-porch dinners with the lake turning pink were the trip." },
  { id: "r13", listingId: "l-beach", author: "Fitsum", date: daysFromNow(-29), rating: 5, text: "Veranda to the water in ninety seconds. Crocs sunbathe exactly where the guidebook promises." },
  { id: "r14", listingId: "l-villa", author: "Mahi", date: daysFromNow(-24), rating: 5, text: "The pool at sunset with both lakes below — we booked another week before we'd even left." },
  { id: "r15", listingId: "l-chalet", author: "Kiros", date: daysFromNow(-38), rating: 5, text: "Geladas took over the meadow at breakfast, entirely unbothered. The cocoa tin is real and endless." },
  { id: "r16", listingId: "l-boat", author: "Almaz", date: daysFromNow(-13), rating: 5, text: "The gentle rocking puts you under like nothing else. Hippos at dusk, at a respectful distance, as promised." },
  { id: "r17", listingId: "l-farm", author: "Tesfay", date: daysFromNow(-18), rating: 5, text: "Eggs from the next field, the falls roaring all day, tej at night. The long table fits everyone." },
  { id: "r18", listingId: "l-farm", author: "Emebet", date: daysFromNow(-57), rating: 4, text: "Idyllic. Rooster is punctual. Would be woken by him again." },
];
