import { addDays, format } from "date-fns";
import type { Booking, Listing, Review, User } from "./types";

export const iso = (d: Date) => format(d, "yyyy-MM-dd");
export const daysFromNow = (n: number) => iso(addDays(new Date(), n));

/* ---------------------------------- images --------------------------------- */
const IMG = {
  aframe: "https://image.qwenlm.ai/generated-images/0d9123ac-4f52-4035-b11e-cce6aabe680b/_result.png",
  loft: "https://image.qwenlm.ai/generated-images/6dc1a153-d6d0-4954-aa5e-1ffd21334140/_result.png",
  beach: "https://image.qwenlm.ai/generated-images/19af859e-08df-48ad-83d7-79f809c92d7c/_result.png",
  treehouse: "https://image.qwenlm.ai/generated-images/7507c55b-1b39-4c49-849b-0b73349a5c01/_result.png",
  villa: "https://image.qwenlm.ai/generated-images/35e769af-6c99-446a-9b21-f7b8d432db85/_result.png",
  chalet: "https://image.qwenlm.ai/generated-images/eb58db7a-655a-4088-bb6c-61a47d6251ca/_result.png",
  casita: "https://image.qwenlm.ai/generated-images/5a092472-92d5-45ec-9f8c-a2089283873b/_result.png",
  houseboat: "https://image.qwenlm.ai/generated-images/2eed9ac6-0733-44c5-97e1-788cb7fd5d93/_result.png",
  farmhouse: "https://image.qwenlm.ai/generated-images/41f2b310-f95e-4f4e-9ba8-5029d3c2296c/_result.png",
  glass: "https://image.qwenlm.ai/generated-images/90a3e478-de91-41e0-849b-1495d32d12c8/_result.png",
};

export const PHOTO_POOL: { src: string; label: string }[] = [
  { src: IMG.aframe, label: "Forest A-frame" },
  { src: IMG.loft, label: "Foundry loft" },
  { src: IMG.beach, label: "Dune house" },
  { src: IMG.treehouse, label: "Treehouse" },
  { src: IMG.villa, label: "Cliff villa" },
  { src: IMG.chalet, label: "Snow chalet" },
  { src: IMG.casita, label: "Desert casita" },
  { src: IMG.houseboat, label: "Houseboat" },
  { src: IMG.farmhouse, label: "Farmhouse" },
  { src: IMG.glass, label: "Glass cabin" },
];

const gallery = (src: string, noun: string) => [
  { caption: `${noun} — main view`, scale: 1, pos: "50% 50%" },
  { caption: "Living area", scale: 1.9, pos: "18% 62%" },
  { caption: "Morning light", scale: 1.7, pos: "78% 30%" },
  { caption: "The details", scale: 2.3, pos: "55% 78%" },
];

/* ---------------------------------- towns ---------------------------------- */
export const TOWNS = [
  { name: "Driftwood Bay", x: 250, y: 168, note: "Surf, fog & fish tacos" },
  { name: "Solstice Harbor", x: 322, y: 305, note: "Marina & night markets" },
  { name: "Old Larchmont", x: 528, y: 332, note: "Brick lanes & roasteries" },
  { name: "Foxglove Valley", x: 468, y: 522, note: "Orchards & slow mornings" },
  { name: "Juniper Flats", x: 716, y: 232, note: "High desert, big sky" },
  { name: "Brindle Peak", x: 782, y: 118, note: "Trailheads & timberline" },
];

export const townCoords = (name: string) => {
  const t = TOWNS.find((t) => t.name === name) ?? TOWNS[0];
  return { x: t.x, y: t.y };
};

/* --------------------------------- amenity meta ----------------------------- */
export const AMENITIES = [
  "Wifi",
  "Kitchen",
  "Free parking",
  "Hot tub",
  "Fireplace",
  "AC",
  "Washer",
  "EV charger",
  "Water access",
  "Sauna",
  "Workspace",
  "Pets allowed",
  "Breakfast basket",
  "Stargazing deck",
];

export const CATEGORIES = [
  "All stays",
  "Cabins",
  "Waterfront",
  "Treehouses",
  "Snow country",
  "Farms & flats",
  "Design",
];

/* ----------------------------------- users ---------------------------------- */
export const hash = (s: string) => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) >>> 0;
  return `h${h.toString(16)}`;
};

export const SEED_USERS: User[] = [
  {
    id: "u-maya",
    name: "Maya Chen",
    email: "host@haven.demo",
    passHash: hash("cedar-dune-8"),
    provider: "email",
    hue: 152,
    superhost: true,
    joined: "2019-04-12",
  },
  {
    id: "u-jonas",
    name: "Jonas Reyes",
    email: "traveler@haven.demo",
    passHash: hash("salt-fern-4"),
    provider: "email",
    hue: 32,
    joined: "2021-09-03",
  },
  { id: "u-theo", name: "Theo Okafor", email: "theo@haven.demo", passHash: hash("x"), provider: "email", hue: 210, superhost: true, joined: "2018-06-21" },
  { id: "u-priya", name: "Priya Nair", email: "priya@haven.demo", passHash: hash("x"), provider: "email", hue: 268, joined: "2020-01-15" },
  { id: "u-elena", name: "Elena Marsh", email: "elena@haven.demo", passHash: hash("x"), provider: "email", hue: 355, superhost: true, joined: "2017-11-02" },
];

/* --------------------------------- listings --------------------------------- */
export const SEED_LISTINGS: Listing[] = [
  {
    id: "l-tree",
    hostId: "u-maya",
    title: "Fern Hollow Treehouse",
    type: "Treehouse",
    town: "Foxglove Valley",
    region: "Cedar Coast",
    price: 196,
    cleaningFee: 65,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 340,
    description:
      "Twenty-two feet up in a heritage fir, Fern Hollow is a one-room hideout reached by rope bridge and lantern light. Mornings arrive as birdsong and valley fog; evenings end on the wraparound deck with the wood stove ticking. The outhouse is a short, fairy-lit walk; the outdoor rain shower is the whole point.",
    amenities: ["Wifi", "Fireplace", "Breakfast basket", "Stargazing deck", "Workspace"],
    photo: IMG.treehouse,
    gallery: gallery(IMG.treehouse, "Fern Hollow"),
    mapX: 440,
    mapY: 500,
    rating: 4.99,
    reviewCount: 301,
    tags: ["Treehouses", "Cabins", "Design"],
    status: "active",
    views: 4180,
    createdAt: "2021-05-14",
  },
  {
    id: "l-casita",
    hostId: "u-maya",
    title: "Juniper Sky Casita",
    type: "Casita",
    town: "Juniper Flats",
    region: "Cedar Coast",
    price: 148,
    cleaningFee: 48,
    guests: 3,
    beds: 1,
    baths: 1,
    sqft: 520,
    description:
      "A hand-troweled adobe roundhouse on three acres of high desert. Thick walls keep it cool at noon and warm at midnight; the turquoise door opens onto a courtyard with a soaking tub pointed straight at the Milky Way. Roadrunners included at no extra charge.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Hot tub", "Pets allowed", "Stargazing deck"],
    photo: IMG.casita,
    gallery: gallery(IMG.casita, "Juniper Sky"),
    mapX: 690,
    mapY: 258,
    rating: 4.94,
    reviewCount: 189,
    tags: ["Farms & flats", "Design"],
    status: "active",
    views: 2644,
    createdAt: "2022-03-02",
  },
  {
    id: "l-glass",
    hostId: "u-maya",
    title: "Northlight Glass Cabin",
    type: "Cabin",
    town: "Old Larchmont",
    region: "Cedar Coast",
    price: 252,
    cleaningFee: 72,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 410,
    description:
      "Four glass walls, one wood stove, zero curtains — Northlight is a study in weather. Watch storms roll over the larch canopy from a sunken reading pit, then let the underfloor heating and a very good espresso machine do the rest. Blackout blinds exist; you'll rarely use them.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Workspace", "EV charger", "Washer"],
    photo: IMG.glass,
    gallery: gallery(IMG.glass, "Northlight"),
    mapX: 578,
    mapY: 276,
    rating: 4.97,
    reviewCount: 240,
    tags: ["Cabins", "Design"],
    status: "active",
    views: 5102,
    createdAt: "2023-01-19",
  },
  {
    id: "l-aframe",
    hostId: "u-theo",
    title: "The Larch A-Frame",
    type: "Cabin",
    town: "Brindle Peak",
    region: "Cedar Coast",
    price: 214,
    cleaningFee: 60,
    guests: 4,
    beds: 2,
    baths: 1,
    sqft: 640,
    description:
      "A 1974 A-frame rebuilt beam by beam at the edge of the larch forest. The triangle window frames the ridge like a painting that changes every hour; the loft bedroom sleeps two under the stars' skylight. Ski trail in winter, wildflower meadow in July — same front door.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Free parking", "Sauna", "Pets allowed"],
    photo: IMG.aframe,
    gallery: gallery(IMG.aframe, "The Larch"),
    mapX: 758,
    mapY: 148,
    rating: 4.96,
    reviewCount: 212,
    tags: ["Cabins", "Snow country", "Design"],
    status: "active",
    views: 3320,
    createdAt: "2020-10-08",
  },
  {
    id: "l-loft",
    hostId: "u-priya",
    title: "Foundry Loft No. 9",
    type: "Loft",
    town: "Old Larchmont",
    region: "Cedar Coast",
    price: 178,
    cleaningFee: 55,
    guests: 2,
    beds: 1,
    baths: 1,
    sqft: 880,
    description:
      "The top floor of the old iron foundry, all arched factory windows and warm brick. Light crosses the oak floor all day long. Two blocks from the roastery row and the Saturday paper market; the record player is stocked and the bathtub is deep.",
    amenities: ["Wifi", "Kitchen", "Washer", "Workspace", "AC"],
    photo: IMG.loft,
    gallery: gallery(IMG.loft, "Foundry Loft"),
    mapX: 536,
    mapY: 310,
    rating: 4.85,
    reviewCount: 98,
    tags: ["Design"],
    status: "active",
    views: 1512,
    createdAt: "2022-08-27",
  },
  {
    id: "l-beach",
    hostId: "u-elena",
    title: "Dune Crest House",
    type: "Beach house",
    town: "Driftwood Bay",
    region: "Cedar Coast",
    price: 342,
    cleaningFee: 110,
    guests: 8,
    beds: 4,
    baths: 3,
    sqft: 2100,
    description:
      "Cedar shingles, sea oats and a boardwalk that ends in the surf. Dune Crest sleeps eight across four quiet bedrooms, with a bunk room the kids will claim first and a screened porch built for long dinners. Fog horns at a distance; coffee on the deck at six.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Washer", "Water access", "Pets allowed", "Breakfast basket"],
    photo: IMG.beach,
    gallery: gallery(IMG.beach, "Dune Crest"),
    mapX: 228,
    mapY: 142,
    rating: 4.92,
    reviewCount: 167,
    tags: ["Waterfront"],
    status: "active",
    views: 2980,
    createdAt: "2019-06-30",
  },
  {
    id: "l-villa",
    hostId: "u-elena",
    title: "Casa Solana",
    type: "Villa",
    town: "Solstice Harbor",
    region: "Cedar Coast",
    price: 410,
    cleaningFee: 140,
    guests: 10,
    beds: 5,
    baths: 4,
    sqft: 3200,
    description:
      "White walls, olive trees and an infinity edge that spills toward the harbor. Casa Solana was built for gatherings — a shaded loggia table seats twelve, the pool faces due west, and the old town's night market is a ten-minute stroll down the cliff path.",
    amenities: ["Wifi", "Kitchen", "Free parking", "AC", "Water access", "Workspace", "EV charger"],
    photo: IMG.villa,
    gallery: gallery(IMG.villa, "Casa Solana"),
    mapX: 300,
    mapY: 282,
    rating: 4.88,
    reviewCount: 76,
    tags: ["Waterfront", "Design"],
    status: "active",
    views: 1874,
    createdAt: "2023-05-11",
  },
  {
    id: "l-chalet",
    hostId: "u-theo",
    title: "Timberline Chalet",
    type: "Chalet",
    town: "Brindle Peak",
    region: "Cedar Coast",
    price: 365,
    cleaningFee: 95,
    guests: 8,
    beds: 4,
    baths: 2,
    sqft: 1900,
    description:
      "Hand-cut timber, a stone hearth you could stand inside, and snow that piles blue against the windows. Timberline sits at the last bend before the ridge trail — ski out in December, hike out in June. The boot room has heated floors; the cocoa tin is never empty.",
    amenities: ["Wifi", "Kitchen", "Fireplace", "Free parking", "Hot tub", "Sauna"],
    photo: IMG.chalet,
    gallery: gallery(IMG.chalet, "Timberline"),
    mapX: 806,
    mapY: 96,
    rating: 4.9,
    reviewCount: 143,
    tags: ["Snow country", "Cabins"],
    status: "active",
    views: 2210,
    createdAt: "2018-12-01",
  },
  {
    id: "l-boat",
    hostId: "u-priya",
    title: "The Wren Houseboat",
    type: "Houseboat",
    town: "Solstice Harbor",
    region: "Cedar Coast",
    price: 226,
    cleaningFee: 58,
    guests: 4,
    beds: 2,
    baths: 1,
    sqft: 560,
    description:
      "Moored in the quiet arm of the harbor, The Wren rocks you to sleep better than any mattress you own. Cedar interior, a tiny galley that does enormous breakfasts, and a rowboat tied alongside for morning loops of the bay. Otters commute past at eight.",
    amenities: ["Wifi", "Kitchen", "Water access", "Breakfast basket", "Pets allowed"],
    photo: IMG.houseboat,
    gallery: gallery(IMG.houseboat, "The Wren"),
    mapX: 352,
    mapY: 344,
    rating: 4.81,
    reviewCount: 64,
    tags: ["Waterfront"],
    status: "active",
    views: 1108,
    createdAt: "2024-02-14",
  },
  {
    id: "l-farm",
    hostId: "u-elena",
    title: "Hollow Oak Farmhouse",
    type: "Farmhouse",
    town: "Foxglove Valley",
    region: "Cedar Coast",
    price: 289,
    cleaningFee: 85,
    guests: 9,
    beds: 4,
    baths: 2,
    sqft: 2600,
    description:
      "A 1908 stone farmhouse at the end of a cypress drive, with a working orchard on one side and the old oak on the other. Eggs arrive from the next field; cider presses in October. The long table in the kitchen has hosted four generations of Sunday lunches.",
    amenities: ["Wifi", "Kitchen", "Free parking", "Fireplace", "Washer", "Pets allowed", "Breakfast basket", "Workspace"],
    photo: IMG.farmhouse,
    gallery: gallery(IMG.farmhouse, "Hollow Oak"),
    mapX: 508,
    mapY: 560,
    rating: 4.87,
    reviewCount: 122,
    tags: ["Farms & flats"],
    status: "active",
    views: 1980,
    createdAt: "2020-04-22",
  },
];

/* --------------------------------- bookings --------------------------------- */
const bk = (
  id: string,
  listingId: string,
  travelerId: string,
  travelerName: string,
  start: number,
  nights: number
): Booking => {
  const listing = SEED_LISTINGS.find((l) => l.id === listingId)!;
  const nightly = nights * listing.price;
  const service = Math.round(nightly * 0.12);
  return {
    id,
    listingId,
    travelerId,
    travelerName,
    checkIn: daysFromNow(start),
    checkOut: daysFromNow(start + nights),
    guests: Math.min(2, listing.guests),
    nights,
    total: nightly + listing.cleaningFee + service,
    breakdown: { nightly, cleaning: listing.cleaningFee, service },
    status: "confirmed",
    createdAt: daysFromNow(start - 12),
  };
};

export const SEED_BOOKINGS: Booking[] = [
  bk("b-1", "l-beach", "u-jonas", "Jonas Reyes", 21, 5),
  bk("b-2", "l-aframe", "u-jonas", "Jonas Reyes", 45, 4),
  bk("b-3", "l-loft", "u-jonas", "Jonas Reyes", -30, 4),
  bk("b-4", "l-tree", "u-theo", "Theo Okafor", 10, 3),
  bk("b-5", "l-glass", "u-elena", "Elena Marsh", 5, 4),
  bk("b-6", "l-casita", "u-priya", "Priya Nair", -12, 3),
  bk("b-7", "l-beach", "u-theo", "Theo Okafor", 30, 4),
  bk("b-8", "l-chalet", "u-jonas", "Jonas Reyes", -60, 3),
];

/* ---------------------------------- reviews --------------------------------- */
export const SEED_REVIEWS: Review[] = [
  { id: "r1", listingId: "l-tree", author: "Amara", date: daysFromNow(-9), rating: 5, text: "The rope bridge at dusk is genuinely magical. Maya left warm bread and local honey — we almost missed checkout on purpose." },
  { id: "r2", listingId: "l-tree", author: "Diego", date: daysFromNow(-41), rating: 5, text: "Best sleep of my life, and I mean that clinically. The rain shower under the canopy sold me forever." },
  { id: "r3", listingId: "l-tree", author: "June", date: daysFromNow(-88), rating: 5, text: "Photos don't do the height justice. Bring a headlamp and zero regrets." },
  { id: "r4", listingId: "l-casita", author: "Tomás", date: daysFromNow(-16), rating: 5, text: "Soaked in the tub under a sky absolutely dense with stars. The adobe stays impossibly cool." },
  { id: "r5", listingId: "l-casita", author: "Wren", date: daysFromNow(-52), rating: 4, text: "Roadrunner woke us at 6am. Five stars for him, four for the thin bedroom curtain." },
  { id: "r6", listingId: "l-glass", author: "Sofia", date: daysFromNow(-7), rating: 5, text: "A storm rolled through on night two and we watched the whole forest bend from the reading pit. Unreal." },
  { id: "r7", listingId: "l-glass", author: "Marcus", date: daysFromNow(-33), rating: 5, text: "The espresso machine alone deserves a review. Worked remotely for a week, zero complaints." },
  { id: "r8", listingId: "l-aframe", author: "Hana", date: daysFromNow(-20), rating: 5, text: "That triangle window is a moving painting. The sauna after a ridge day — perfection." },
  { id: "r9", listingId: "l-aframe", author: "Piotr", date: daysFromNow(-64), rating: 5, text: "Cozy is an overused word; this earns it. Firewood stacked, loft warm, snow silent." },
  { id: "r10", listingId: "l-loft", author: "Leila", date: daysFromNow(-11), rating: 5, text: "Light moves through those factory windows all day. The record collection got heavy rotation." },
  { id: "r11", listingId: "l-loft", author: "Owen", date: daysFromNow(-47), rating: 4, text: "Gorgeous space, street noise on market mornings — bring earplugs or join the crowd." },
  { id: "r12", listingId: "l-beach", author: "Nadia", date: daysFromNow(-5), rating: 5, text: "Eight of us, zero collisions. The screened porch dinners were the trip." },
  { id: "r13", listingId: "l-beach", author: "Callum", date: daysFromNow(-29), rating: 5, text: "Boardwalk to the surf in ninety seconds. The bunk room is kid catnip." },
  { id: "r14", listingId: "l-villa", author: "Ingrid", date: daysFromNow(-24), rating: 5, text: "The pool at sunset with the harbor below — we booked another week before leaving." },
  { id: "r15", listingId: "l-chalet", author: "Rafael", date: daysFromNow(-38), rating: 5, text: "Ski out the door, hot tub under snowfall. The cocoa tin is real and it is endless." },
  { id: "r16", listingId: "l-boat", author: "Bea", date: daysFromNow(-13), rating: 5, text: "The gentle rocking puts you under like nothing else. Otters at 8am sharp, as promised." },
  { id: "r17", listingId: "l-farm", author: "Gus", date: daysFromNow(-18), rating: 5, text: "Eggs from next field, cider pressing the weekend we stayed. The long table fits everyone." },
  { id: "r18", listingId: "l-farm", author: "Yuki", date: daysFromNow(-57), rating: 4, text: "Idyllic. Rooster is punctual. Would be woken by him again." },
];
